# Generated by Django 2.2 on 2020-07-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Tittle')),
                ('text', models.TextField(verbose_name='Text')),
                ('published_at', models.DateTimeField(verbose_name='Publish date')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ('-published_at',),
            },
        ),
    ]
