# Generated by Django 2.2 on 2020-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200804_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0, verbose_name='Order price'),
        ),
    ]
